branch-defaults:
  main:
    environment: gha-course-staging
    group_suffix: null
global:
  application_name: nextjs-starter
  branch: null
  default_ec2_keyname: weblogkp
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
